// This file is auto-generated by @hey-api/openapi-ts

import type { DefaultError, MutationOptions } from '@tanstack/svelte-query';

import { create, double, type Options } from '../sdk.gen';
import type { CreateData, CreateError, DoubleData, DoubleResponse } from '../types.gen';

export const createMutation = (options?: Partial<Options<CreateData>>): MutationOptions<unknown, CreateError, Options<CreateData>> => {
    const mutationOptions: MutationOptions<unknown, CreateError, Options<CreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const doubleMutation = (options?: Partial<Options<DoubleData>>): MutationOptions<DoubleResponse, DefaultError, Options<DoubleData>> => {
    const mutationOptions: MutationOptions<DoubleResponse, DefaultError, Options<DoubleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await double({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
