// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { create, double, get, type Options, test } from '../sdk.gen';
import type { CreateData, CreateError, DoubleData, DoubleResponse, GetData, GetError, GetResponse, TestData, TestError } from '../types.gen';

export const createMutation = (options?: Partial<Options<CreateData>>): MutationOptions<unknown, CreateError, Options<CreateData>> => {
    const mutationOptions: MutationOptions<unknown, CreateError, Options<CreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await create({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getQueryKey = (options: Options<GetData>) => createQueryKey('get', options);

export const getOptions = (options: Options<GetData>) => queryOptions<GetResponse, GetError, GetResponse, ReturnType<typeof getQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await get({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getQueryKey(options)
});

export const testMutation = (options?: Partial<Options<TestData>>): MutationOptions<unknown, TestError, Options<TestData>> => {
    const mutationOptions: MutationOptions<unknown, TestError, Options<TestData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await test({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const doubleMutation = (options?: Partial<Options<DoubleData>>): MutationOptions<DoubleResponse, DefaultError, Options<DoubleData>> => {
    const mutationOptions: MutationOptions<DoubleResponse, DefaultError, Options<DoubleData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await double({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
