// This file is auto-generated by @hey-api/openapi-ts

export { create, double, get, type Options, test } from './sdk.gen';
export type { Body, ClientOptions, CreateData, CreateError, CreateErrors, CreateGameRequest, CreateResponses, DoubleData, DoubleResponse, DoubleResponses, GamePublic, GetData, GetError, GetErrors, GetResponse, GetResponses, Player, ProblemDetails, TestData, TestError, TestErrors, TestRequest, TestResponses } from './types.gen';
