// This file is auto-generated by @hey-api/openapi-ts

export { create, double, type Options } from './sdk.gen';
export type { Body, ClientOptions, CreateData, CreateError, CreateErrors, CreateGameRequest, CreateResponses, DoubleData, DoubleResponse, DoubleResponses, ProblemDetails } from './types.gen';
