// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type Body = {
    value?: number;
};

export type CreateGameRequest = {
    id?: string;
    name?: string;
    products?: Array<string>;
};

export type ProblemDetails = {
    type?: string;
    title?: string;
    status?: number | null;
    detail?: string;
    instance?: string;
    extensions?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type CreateData = {
    body: CreateGameRequest;
    headers: {
        /**
         * Player UUID
         */
        'Player-Id': string;
    };
    path?: never;
    query?: never;
    url: '/Create';
};

export type CreateErrors = {
    /**
     * Payload of ProblemDetails
     */
    400: ProblemDetails;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * No description
     */
    200: unknown;
};

export type DoubleData = {
    body: Body;
    path?: never;
    query?: never;
    url: '/Double';
};

export type DoubleResponses = {
    /**
     * Payload of Body
     */
    200: Body;
};

export type DoubleResponse = DoubleResponses[keyof DoubleResponses];
