// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type Body = {
    value?: number;
};

export type CreateGameRequest = {
    id?: string;
    name?: string;
    createdBy?: Player;
    products?: Array<string>;
};

export type GamePublic = {
    createdBy?: string | null;
    players?: Array<string> | null;
    id?: string | null;
    name?: string | null;
    state?: 'PlayerRegistration' | 'GameStarted' | 'GameOver';
    createdAt?: string | null;
    products?: Array<string> | null;
};

export type Player = {
    id?: string;
    name?: string;
};

export type ProblemDetails = {
    type?: string;
    title?: string;
    status?: number | null;
    detail?: string;
    instance?: string;
    extensions?: {
        [key: string]: {
            [key: string]: unknown;
        };
    };
};

export type TestRequest = {
    gameId?: string;
    testString?: string;
};

export type CreateData = {
    body: CreateGameRequest;
    headers: {
        /**
         * Player UUID
         */
        'Player-Id': string;
    };
    path?: never;
    query?: never;
    url: '/Create';
};

export type CreateErrors = {
    /**
     * Payload of ProblemDetails
     */
    400: ProblemDetails;
    /**
     * Payload of ProblemDetails
     */
    409: ProblemDetails;
};

export type CreateError = CreateErrors[keyof CreateErrors];

export type CreateResponses = {
    /**
     * No description
     */
    200: unknown;
};

export type GetData = {
    body?: never;
    headers: {
        /**
         * Player UUID
         */
        'Player-Id': string;
    };
    path: {
        /**
         * Game id
         */
        id: string;
    };
    query?: never;
    url: '/games/{id}';
};

export type GetErrors = {
    /**
     * Payload of ProblemDetails
     */
    404: ProblemDetails;
};

export type GetError = GetErrors[keyof GetErrors];

export type GetResponses = {
    /**
     * Payload of GamePublic
     */
    200: GamePublic;
};

export type GetResponse = GetResponses[keyof GetResponses];

export type TestData = {
    body: TestRequest;
    headers: {
        /**
         * Player UUID
         */
        'Player-Id': string;
    };
    path?: never;
    query?: never;
    url: '/games/test';
};

export type TestErrors = {
    /**
     * Payload of ProblemDetails
     */
    400: ProblemDetails;
};

export type TestError = TestErrors[keyof TestErrors];

export type TestResponses = {
    /**
     * No description
     */
    200: unknown;
};

export type DoubleData = {
    body: Body;
    path?: never;
    query?: never;
    url: '/Double';
};

export type DoubleResponses = {
    /**
     * Payload of Body
     */
    200: Body;
};

export type DoubleResponse = DoubleResponses[keyof DoubleResponses];
